### ISSUE TITLE
Upgrade antipatterns

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/RSBot-API#1611]
Current client antipatterns don't do much and they might disrupt the execution of scripts. I propose the addition of non-interfering antipatterns. Each user would get a randomly generated pattern profile which would be stored on the server (or just locally on their computer) and loaded when they start the script. The pattern profile could also be slightly adjusted between runs for things like fatigue, the frequency of certain actions, clicking accuracy, etc... . 

Here are a few "patterns" that could be implemented directly into the client:
- Closing interfaces with mouse (clicking the "X") or keyboard (pressing ESC button).
- Clicking accuracy (next point calculation deviation).
- Continuing chat with mouse or keyboard.
- Energy limit for turning on running.

Script writers would also have the ability to store their own patterns in the profile. This would make writing custom antipatterns much easier because right now we have to override client methods/write our own custom implementations to add things like the ones written above, which could be added into the client by adding one or two new lines of code. And many script writers don't even implement any antipatterns so this would automatically add a base layer of protection.

## Phase one
- [ ] Implement Break Handler
- [x] Add universal interface closing method (#1647)
- [ ] Implement Antipatterns API
  - [ ] Save/load patterns
  - [ ] Option to clear and recalculate new patterns
- [ ] Overloaded closing methods with hotkey support
  - [x] Deposit boxes (rt4 & rt6) (#1670)
- [x] Add hotkey support for game tab switching (rt4)
  - [x] Add keybinds API (#1620)
  - [x] Implement hotkey support (#1620)
- [ ] Add RS3 hotkey support (#1639)
- [ ] Add support for camera rotations with mouse
- [ ] Implement additional game settings checks
  - [x] ESC closing enabled (rt4) (#1620)
- [ ] Add in-game world switching support rt6
- [x] Mouse scrolling support rt4 (#1622)
- [ ] Add Hud menu/window/subtab support for all game mode combinations (legacy combat & eoc interface, and vice versa)

**Comment by MrFreezerburnt** [comment]
Closing interfaces with ESC requires a certain option toggled to work (for rt4 at least, I couldn't find a toggle for rt6 but it works). Should devs consider this, check if they have the option selected. Here's the varpbit for rt4:

`1224 - 1145077760 (0x44408000) -> -1002405888 (0xc4408000)`

**Comment by ArtificialPB** [comment]
@MrFreezerburnt That's the plan, to randomize usage of what the user has enabled. To add to your comment, some interfaces like rt4 bank must always be closed by mouse, regardless of whether they have the hotkey setting enabled or not.

**Comment by ArtificialPB** [comment]
To clarify a couple of things, this is NOT meant to force everyone to use all of the client-side antipatterns. Antipatterns like closing bank with either ESC key or mouse click would be available by default (implemented in Bank#close() for example), but script writers would still be able to bypass them by using the overloaded methods (Bank#close(boolean) in this case) for whatever reasons.

There would be however some things that script writers would not be able to change like clicking point randomization (nextPoint()). Basically the things that the client already does for you, but this would be minimal.

**Comment by ArtificialPB** [comment]
I'll start making a plan with things to implement next week. If you have any suggestions/questions/concerns, feel free to post them here or contact me on Slack.

**Comment by rs-sliske** [comment]
whether the new pattern is any better or worse on its own doesnt really make much difference

the problem with changing the default behavior of the client is that the pattern changes for every bot at the same time (which itself feels like a pretty obvious pattern, especially given that the new pattern isnt really any more efficient)

looking at the commits that were made, it doesnt look like there is any checking for if the user has the option enabled, or remembering whether the user is going to use escape/mouse for closing bank. it is just calling Random.nextBoolean every time close gets called

even the parameter coma added to allow script writers to implement something like that themselves was removed by paris

**Comment by ArtificialPB** [comment]
@rs-sliske Hotkey closing was only added to RS3 for now, and afaik you can always close the bank with ESC there. I don't know why that parameter was removed (@Paris), overloaded methods should be provided to "bypass" the antipatterns if you have to for whatever reason.

**Comment by rs-sliske** [comment]
pressing the escape key once wont always close the bank on rs3

ok its not a major thing to have to call close multiple times, except that it now tosses a coin every time it tries to close the bank 
(maybe this could be a new game mode :p, instead of ironman where you cant trade. you could have coinman, every time you want to perform an action, you have to toss a coin to decide if you should use your mouse or keyboard for it :) )

**Comment by ArtificialPB** [comment]
Added a plan for the phase one, which is meant to implement the framework for the later implementation of patterns (phase two). This will not modify current behavior in any way. You're more than welcome to post your own suggestions or open a PR addressing one of the points.

**Comment by ChrisBPB** [comment]
What would be pretty sweet is if the user could perform an initial set up for their first time using RSBot, and they could select whether they use escape or X etc so the bot would mimic the actual user of the account.

**Comment by MrFreezerburnt** [comment]
tbh having a user settings file could be beneficial

**Comment by ArtificialPB** [comment]
@ChrisBPB I agree, this will be implemented in phase two.

@MrFreezerburnt This will be implemented with the Antipatterns API (check out the list in the first post).

**Comment by dfreelan** [comment]
Are you guys still working on implmenting something like this?

If yall want help, setting all the functions in Input.java to allowed to be overridden (get rid of final modifier....)   I can assist. I'm making a set of antipatterns using symbolic regression.

However, currently I have to test it by making my code entirely separately from the client and it's quite inconvenient :P

**Comment by ChrisBPB** [comment]
@dfreelan we appreciate any and all input, this particular task is all based around the API which is open sourced here, so feel free to open up any pull requests

please bare in mind that we do tend to try and mirror changes to match both rt4 and rt6 with the exception of if it doesn't exist (i.e shift dropping doesnt exist in rt6)

**Comment by Paris** [comment]
Most of these would be redundant now but we will still focus on #1965.
